swagger: '3.0'
info:
  version:  1.0.0
  title: RESTful接口
  description: RESTful API
  termsOfService: ""
  contact:
    name: 付红竹
    url: http://mi1024.top
    email: rootfuhz@163.com

host: localhost:8520
basePath: /onecity/v1
schemes:
- https
- http

consumes:
- application/json
produces:
- application/json

securityDefinitions:
  APIToken:
    type: apiKey
    in: header
    name: X-API-TOKEN

security:
- APIToken: []

definitions:
  ApiResponse:
    properties:
      error_code:
        type: integer
      data:
        type: string
      msg:
        type: string


  ErrorResponse:
    type: object
    properties:
      error_code:
        type: integer
      msg:
        type: string
      request:
        type: string



paths:
  /register:
    post:
      tags:
        - 用户
      summary: 注册新用户
      security: []
      parameters:
        - name: user
          in: body
          description: 创建用户
          schema:
            properties:
              nickname:
                type: string
                minLength: 2
                maxLength: 16
              password:
                type: string
                pattern: ^[A-Za-z0-9_*&$#@]{6,22}$
                minLength: 6
                maxLength: 24
      responses:
        200:
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiResponse'
        default:
          description: 操作异常,执行失败.返回信息描述错误详情
          schema:
            $ref: '#/definitions/ErrorResponse'

  /login:
    post:
      tags:
        - 用户
      summary: 登陆
      security: []
      parameters:
        - name: user
          in: body
          description: 登陆
          schema:
            properties:
              nickname:
                type: string
              password:
                type: string
      responses:
        200:
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiResponse'
        default:
          description: 操作异常,执行失败.返回信息描述错误详情
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user/information:
    get:
      tags:
        - 用户
      summary: 获取用户自己信息
      responses:
        200:
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiResponse'
        default:
          description: 操作异常,执行失败.返回信息描述错误详情
          schema:
            $ref: '#/definitions/ErrorResponse'




