"""users table

Revision ID: 5a02b396fe06
Revises: e3c38ec30de9
Create Date: 2019-04-17 17:33:35.842284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a02b396fe06'
down_revision = 'e3c38ec30de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###
